# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Rectue CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      # Postgres Test DB
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test_postgres
          POSTGRES_PASSWORD: test_postgres
          POSTGRES_DB: test_db

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
      redis:
        image: redis
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        shell: bash
        working-directory: server
    steps:
      - uses: actions/checkout@v2
      - name: Rectue v.0.0.1
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run test
        env:
          CI: true
          SALT: 10
          TEST_PORT: 4001
          PORT: 4000
          LOCAL_PORT: 4002
          LOCAL_TEST_PORT: 4003
