# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rectue v.0.0.1
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: cd server
    - run: npm install
    - run: npm run test
      env:
        CI: true
